[package]
name = "rest-client_codegen"
version = "0.1.0"
authors = ["Michl Steglich <mrgreaka@gmail.com>"]
edition = "2018"
workspace = "../"

[lib]
proc-macro = true

[dependencies]
hyper = "0.12"
hyper-tls = "0.3"
proc-macro2 = "0.4"
syn = { version = "0.15", features = ["full"] }
quote = "0.6"
